### ISSUE TITLE
Error: Tazmoticz: AttributeError: type object 'Collection' has no attribute 'Mapping' with Python 3.10.4

### ISSUE THREAD

**Issue by CyrilB1531** [joba-1/Tasmoticz#30]
Is it possible to change tasmota.py file to use collections.abc.Mapping instead of collections.Mapping?

**Comment by joba-1** [comment]
I don't think so.
It is a type used by the domoticz api, not my choice.

**Comment by CyrilB1531** [comment]
Since, I've made this changes in the plugin error disapears and Tazmoticz detects all my temperature sensors from now.
And I can push my changes if you want

**Comment by joba-1** [comment]
cool, so domoticz changed its api. Then no problem, PR or code example are very welcome. I just need to find out how to make it backwards compatible.

**Comment by CyrilB1531** [comment]
I've just add backward compatibilty on the PR. Please let me know if the fix is good for you

**Comment by joba-1** [comment]
just tested and merged - works fine with my dated domoticz Version: 2020.2 (build 12173) and Python 3.6.15.

Thanks!
